### ISSUE TITLE
Negação de acesso

### ISSUE THREAD

**Issue by KevinPloc** [MrEmpy/1nf0-hunt3r#1]
Infelizmente, sempre que tento acessar a ferramenta, o mesmo nega totalmente meu acesso. Não sei se é por causa do Root, ou não, pois eu não sou " Usuário Root " embora, eu não sei como funciona. Poderia me ajudar por favor? 
![Screenshot_20201231-090447](https://user-images.githubusercontent.com/76752658/103409804-422def80-4b47-11eb-89ee-82a512e5cb54.png)

**Comment by brosck** [comment]
Não precisa digitar "python3 1nf0-hunt3r.py". Você tem que digitar "1nf0_hunt3r.py", o erro aconteceu porque você digitou o "-" alem do "_".
