### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by supremepo** [MrEmpy/1nf0-hunt3r#2]
Não sei o que aconteceu, quando tento por o código aparece isso o devo fazer?
![Screenshot_20210125-021149](https://user-images.githubusercontent.com/77952511/105664498-9365a080-5eb3-11eb-9a42-74f62c1fc684.png)

**Comment by brosck** [comment]
Vc nn tem o python3 instalado por isso dá esse erro

**Comment by supremepo** [comment]
Ok obg

**Comment by brosck** [comment]
É nois
